version: '3.8'
services:
  linkshare:
    image: linkshare
    container_name: linkshare
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT="production"
    working_dir: /code
    networks:
      - proxy-manager_default
    ports:
      - 127.0.0.1:8000:80
    restart: unless-stopped
    build: .
    # volumes:
    #   - ./data:/code/data

networks:
  proxy-manager_default:
    external: true
